[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[project]
name = "wenyan"
dynamic = ["version"]
description = "Programming Language for the ancient Chinese"
requires-python = ">=3.7"
authors = [{ name = "Tang Ziya", email = "tcztzy@gmail.com" }]
classifiers = [
    "Development Status :: 1 - Planning",
    "License :: OSI Approved :: MIT License",
    "Natural Language :: Chinese (Traditional)",
    "Programming Language :: Other",
    "Programming Language :: Rust",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
]
dependencies = [
    "importlib-metadata; python_version<'3.8'",
    "lark>=1.1.5",
]

[project.optional-dependencies]
dev = ["pre-commit"]

[tool.setuptools_scm]
write_to = "wenyan/_version.py"
